Upload Key Pair

diff --git a/.github/workflows/deploy_ec2.yml b/.github/workflows/deploy_ec2.yml
--- a/.github/workflows/deploy_ec2.yml
+++ b/.github/workflows/deploy_ec2.yml
@@ -138,7 +138,7 @@ jobs:
     - name: Get EC2 Public IP
       id: get_ip
       run: |
-            PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
+            PPUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Jenkins" --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
             echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
 
     - name: Upload Key Pair
@@ -164,9 +164,20 @@ jobs:
       env:
         PUBLIC_IP: ${{ needs.deploy-ec2.outputs.public_ip }}
       run: |
-          chmod 400 ${{ env.KEY_NAME }}.pem
-          scp -i jenkins.pem -o StrictHostKeyChecking=no 00_ec2/ec2_user_data.sh ubuntu@$PUBLIC_IP:/home/ubuntu/
-          ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$PUBLIC_IP 'chmod +x /home/ubuntu/ec2_user_data.sh && sudo /home/ubuntu/ec2_user_data.sh'
+        if [ -z "$PUBLIC_IP" ]; then
+         echo "Error: PUBLIC_IP is not set"
+        exit 1
+        fi
+    
+        # Verificar que el archivo jenkins.pem existe
+        if [ ! -f "jenkins.pem" ]; then
+         echo "Error: jenkins.pem not found"
+         ls -la
+         exit 1
+        fi
+        chmod 400 jenkins.pem
+        scp -i jenkins.pem -o StrictHostKeyChecking=no 00_ec2/ec2_user_data.sh ubuntu@$PUBLIC_IP:/home/ubuntu/
+        ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$PUBLIC_IP 'chmod +x /home/ubuntu/ec2_user_data.sh && sudo /home/ubuntu/ec2_user_data.sh'
 
   create-eks-cluster:
     needs: [deploy-ec2, setup-ec2]
